base = "materials::subscribed_tea"

[[rulesets]]
[rulesets.rules]
"arabica cherry wine" = "阿拉比卡咖啡樱桃酒"
"arabica coffee bean" = "阿拉比卡咖啡豆"
"arabica coffee beans" = "阿拉比卡咖啡豆"
"arabica coffee cherries" = "阿拉比卡咖啡樱桃"
"arabica coffee cherry" = "阿拉比卡咖啡樱桃"
"arabica coffee tree" = "阿拉比卡咖啡树"
"arabica wood" = "阿拉比卡咖啡木材"
"berries" = "浆果"
"boiling arabica cherry wine" = "沸腾的阿拉比卡咖啡樱桃酒"
"boiling arabica coffee" = "沸腾的阿拉比卡咖啡"
"boiling green tea" = "沸腾的绿茶"
"boiling guarana tea" = "沸腾的瓜拉纳茶"
"boiling robusta cherry wine" = "沸腾的罗布斯塔咖啡樱桃酒"
"boiling robusta coffee" = "沸腾的罗布斯塔咖啡"
"boiling tea" = "沸腾的茶"
"boiling yaupon tea" = "沸腾的美洲冬青茶"
"boiling yerba mate tea" = "沸腾的马黛茶"
"brew drink from buds" = "用嫩芽冲泡饮料"
"brew drink from grounds" = "用粉末冲泡饮料"
"Brewable coffees and teas for your dwarves!" = "为矮人提供可冲泡的咖啡与茶！"
"brewed arabica coffee" = "冲泡的阿拉比卡咖啡"
"brewed robusta coffee" = "冲泡的罗布斯塔咖啡"
"caffeination" = "咖啡因兴奋"
"coffee bean dye" = "咖啡豆染料"
"coffee flower cluster" = "咖啡花簇"
"coffee leaf" = "咖啡叶"
"coffee leaves" = "咖啡叶"
"Dwarven Tea Party" = "矮人茶会"
"frozen arabica cherry wine" = "结冻的阿拉比卡咖啡樱桃酒"
"frozen arabica coffee" = "结冻的阿拉比卡咖啡"
"frozen green tea" = "结冻的绿茶"
"frozen guarana tea" = "结冻的瓜拉纳茶"
"frozen robusta cherry wine" = "结冻的罗布斯塔咖啡樱桃酒"
"frozen robusta coffee" = "结冻的罗布斯塔咖啡"
"frozen tea" = "结冻的茶"
"frozen yaupon tea" = "结冻的美洲冬青茶"
"frozen yerba mate tea" = "结冻的马黛茶"
"grind caffeinated fruit" = "研磨含咖啡因的果实"
"grind caffeinated seeds" = "研磨含咖啡因的种子"
"ground arabica coffee" = "研磨的阿拉比卡咖啡"
"ground guarana seed" = "研磨的瓜拉纳种子"
"ground robusta coffee" = "研磨的罗布斯塔咖啡"
"guarana flower cluster" = "瓜拉纳花簇"
"guarana fruit" = "瓜拉纳果实"
"guarana leaf" = "瓜拉纳叶"
"guarana leaves" = "瓜拉纳叶"
"guarana plant" = "瓜拉纳植株"
"guarana seed" = "瓜拉纳种子"
"guarana seeds" = "瓜拉纳种子"
"make coffee bean dye" = "制作咖啡豆染料"
"make tea leaf dye" = "制作茶叶染料"
"process caffeinated fruit for seeds" = "加工含咖啡因的果实以获取种子"
"robusta cherry wine" = "罗布斯塔咖啡樱桃酒"
"robusta coffee bean" = "罗布斯塔咖啡豆"
"robusta coffee beans" = "罗布斯塔咖啡豆"
"robusta coffee cherries" = "罗布斯塔咖啡樱桃"
"robusta coffee cherry" = "罗布斯塔咖啡樱桃"
"robusta coffee tree" = "罗布斯塔咖啡树"
"robusta wood" = "罗布斯塔咖啡木材"
"steeped green tea" = "浸泡的绿茶"
"steeped guarana tea" = "浸泡的瓜拉纳茶"
"steeped tea" = "浸泡的茶"
"steeped yaupon tea" = "浸泡的美洲冬青茶"
"steeped yerba mate tea" = "浸泡的马黛茶"
"tea flower" = "茶花"
"tea leaf" = "茶叶"
"tea leaf bud" = "茶叶芽"
"tea leaf dye" = "茶叶染料"
"tea leaves" = "茶叶"
"tea seed" = "茶种子"
"tea seeds" = "茶种子"
"tea tree" = "茶树"
"tea tree capsule" = "茶树蒴果"
"tea wood" = "茶树木材"
"yaupon berries" = "美洲冬青浆果"
"yaupon berry" = "美洲冬青浆果"
"yaupon flower" = "美洲冬青花"
"yaupon leaf" = "美洲冬青叶"
"yaupon leaf bud" = "美洲冬青叶芽"
"yaupon leaves" = "美洲冬青叶"
"yaupon seed" = "美洲冬青种子"
"yaupon seeds" = "美洲冬青种子"
"yaupon tree" = "美洲冬青树"
"yaupon wood" = "美洲冬青木材"
"yerba mate berry" = "马黛浆果"
"yerba mate flower" = "马黛花"
"yerba mate leaf" = "马黛叶"
"yerba mate leaf bud" = "马黛叶芽"
"yerba mate leaves" = "马黛叶"
"yerba mate seed" = "马黛种子"
"yerba mate seeds" = "马黛种子"
"yerba mate tree" = "马黛树"
"yerba mate wood" = "马黛木材"
"arabica coffee trees" = "阿拉比卡咖啡树"
"guarana plants" = "瓜拉纳植株"
"robusta coffee trees" = "罗布斯塔咖啡树"
"tea trees" = "茶树"
"yaupon trees" = "美洲冬青树"
"yerba mate trees" = "马黛树"
