base = "fumo_item::items"

[[rulesets]]
[rulesets.rules]
"cirno fumo" = "琪露诺 Fumo 玩偶"
"cirno fumos" = "琪露诺 Fumo 玩偶"
"reimu fumo" = "灵梦 Fumo 玩偶"
"reimu fumos" = "灵梦 Fumo 玩偶"
"marisa fumo" = "魔理沙 Fumo 玩偶"
"marisa fumos" = "魔理沙 Fumo 玩偶"
"neco arc fumo" = "猫弧 Fumo 玩偶"
"neco arc fumos" = "猫弧 Fumo 玩偶"
"rumia fumo" = "露米娅 Fumo 玩偶"
"rumia fumos" = "露米娅 Fumo 玩偶"
"meiling fumo" = "美铃 Fumo 玩偶"
"meiling fumos" = "美铃 Fumo 玩偶"
"patchouli fumo" = "帕秋莉 Fumo 玩偶"
"patchouli fumos" = "帕秋莉 Fumo 玩偶"
"sakuya fumo" = "咲夜 Fumo 玩偶"
"sakuya fumos" = "咲夜 Fumo 玩偶"
"remilia fumo" = "蕾米莉亚 Fumo 玩偶"
"remilia fumos" = "蕾米莉亚 Fumo 玩偶"
"flandre fumo" = "芙兰朵露 Fumo 玩偶"
"flandre fumos" = "芙兰朵露 Fumo 玩偶"
"youmu fumo" = "妖梦 Fumo 玩偶"
"youmu fumos" = "妖梦 Fumo 玩偶"
"yuyuko fumo" = "幽幽子 Fumo 玩偶"
"yuyuko fumos" = "幽幽子 Fumo 玩偶"
"alice fumo" = "爱丽丝 Fumo 玩偶"
"alice fumos" = "爱丽丝 Fumo 玩偶"
"daiyousai fumo" = "大妖精 Fumo 玩偶"
"daiyousai fumos" = "大妖精 Fumo 玩偶"

[[rulesets]]
name = "recipe"
[rulesets.rules]
"make Cirno fumo" = "制作琪露诺 Fumo 玩偶"
"make Reimu fumo" = "制作灵梦 Fumo 玩偶"
"make Marisa fumo" = "制作魔理沙 Fumo 玩偶"
"make Neco Arc fumo" = "制作猫弧 Fumo 玩偶"
"make Rumia fumo" = "制作露米娅 Fumo 玩偶"
"make Meiling fumo" = "制作美铃 Fumo 玩偶"
"make Patchouli fumo" = "制作帕秋莉 Fumo 玩偶"
"make Sakuya fumo" = "制作咲夜 Fumo 玩偶"
"make Remilia fumo" = "制作蕾米莉亚 Fumo 玩偶"
"make Flandre fumo" = "制作芙兰朵露 Fumo 玩偶"
"make Youmu fumo" = "制作妖梦 Fumo 玩偶"
"make Yuyuko fumo" = "制作幽幽子 Fumo 玩偶"
"make Alice fumo" = "制作爱丽丝 Fumo 玩偶"
"make Daiyousei fumo" = "制作大妖精 Fumo 玩偶"
