# Dwarvemon 2.22 translation extension; merges into the base namespace.
base = "items::helm"

[[rulesets]]
name = "main"
[rulesets.rules]
"{::items::dwarvemon::helm}" = "{::items::dwarvemon::helm}"

[[rulesets]]
name = "singular::main"
[rulesets.rules]
"{::items::dwarvemon::helm}" = "{::items::dwarvemon::helm}"

[[rulesets]]
name = "plural::main"
[rulesets.rules]
"{::items::dwarvemon::helm}" = "{::items::dwarvemon::helm}"
