base = "creatures::name"

[[rulesets]]
name = "singular"
[rulesets.rules]
"{::creatures::subscribed_rituals}" = "{::creatures::subscribed_rituals}"

[[rulesets]]
name = "plural"
[rulesets.rules]
"{::creatures::subscribed_rituals}" = "{::creatures::subscribed_rituals}"

