base = "creatures::subscribed_rituals"

[[rulesets]]
[rulesets.rules]
"{cleric}" = "{cleric}"
"{undead}" = "{undead}"

[[rulesets]]
name = "cleric"
[rulesets.rules]
"{title} of {@bt_god}" = "{@bt_god}的{title}"
"{@bt_god}'s {title}" = "{@bt_god}的{title}"

[[rulesets]]
name = "title"
[rulesets.rules]
"Thrall" = "仆从"
"Buzzard" = "秃鹰祭司"
"Druid" = "德鲁伊"
"Ovate" = "卜者"
"Chosen" = "神选者"
"Pebble" = "卵石祭司"
"Vessel" = "神力容器"
"Magus" = "魔导师"
"Priest" = "祭司"
"Cleric" = "神官"
"River" = "河流祭司"
"Vassal" = "侍臣"
"Blaze" = "烈焰祭司"
"Squire" = "扈从"
"Ward" = "守护者"
"Bard" = "吟游诗人"
"Servant" = "侍者"
"necromancer" = "死灵法师"
"Thralls" = "仆从"
"Buzzards" = "秃鹰祭司"
"Druids" = "德鲁伊"
"Ovates" = "卜者"
"Chosens" = "神选者"
"Pebbles" = "卵石祭司"
"Vessels" = "神力容器"
"Maguss" = "魔导师"
"Priests" = "祭司"
"Clerics" = "神官"
"Rivers" = "河流祭司"
"Vassals" = "侍臣"
"Blazes" = "烈焰祭司"
"Squires" = "扈从"
"Wards" = "守护者"
"Bards" = "吟游诗人"
"Servants" = "侍者"
"necromancers" = "死灵法师"

[[rulesets]]
name = "undead"
[rulesets.rules]
"{undead_adjective} {undead_noun}" = "{undead_adjective}{undead_noun}"

[[rulesets]]
name = "undead_adjective"
[rulesets.rules]
"night" = "暗夜"
"risen" = "复起的"
"sunless" = "无日的"
"dark" = "黑暗"
"pale" = "苍白"
"returned" = "归来的"
"hollow" = "空洞"
"cold" = "冰冷"
"gaunt" = "憔悴"
"doomed" = "注定覆灭的"
"death" = "死亡"
"empty" = "空虚"
"void" = "虚无"
"fallen" = "堕落"
"fell" = "凶恶"
"cursed" = "受诅咒的"
"damned" = "被神遗弃的"
"lost" = "迷失"
"ruined" = "残破"
"dismal" = "阴郁"
"fetid" = "恶臭"
"rotten" = "腐烂"
"putrid" = "腐臭"
"corrupted" = "腐化"
"bitter" = "苦怨"
"bleak" = "凄凉"
"frozen" = "冰冻"
"faded" = "黯淡"
"faint" = "隐约"
"sallow" = "蜡黄"
"forlorn" = "孤寂"
"grim" = "阴森"
"wasting" = "衰朽"
"blighted" = "疫败"
"infected" = "感染"
"diseased" = "患病"
"poisoned" = "中毒"
"tainted" = "污秽"
"plague" = "瘟疫"

[[rulesets]]
name = "undead_noun"
[rulesets.rules]
"one" = "亡者"
"corpse" = "尸体"
"ghoul" = "食尸鬼"
"zombie" = "僵尸"
"stalker" = "潜行者"
"butcher" = "屠夫"
"hunter" = "猎手"
"slayer" = "杀戮者"
"thrall" = "仆从"
"haunt" = "幽魂"
"shade" = "暗影"
"wraith" = "怨灵"
"spirit" = "灵体"
"ones" = "亡者"
"corpses" = "尸体"
"ghouls" = "食尸鬼"
"zombies" = "僵尸"
"stalkers" = "潜行者"
"butchers" = "屠夫"
"hunters" = "猎手"
"slayers" = "杀戮者"
"thralls" = "仆从"
"haunts" = "幽魂"
"shades" = "暗影"
"wraiths" = "怨灵"
"spirits" = "灵体"

[[rulesets]]
name = "action"
[rulesets.rules]
"Raise {undead}" = "复活{undead}"
"Pray for a pet from {@bt_god}" = "向{@bt_god}祈求宠物"
"pray for a pet from {@bt_god}" = "向{@bt_god}祈求宠物"
"is blessed by {@bt_god} with a pet" = "获{@bt_god}赐予宠物"

