base = "materials::subscribed_blessings"

[[rulesets]]
[rulesets.rules]
"1 Blessing of Rapid Regeneration" = "1 快速再生祝福"
"2 Blessing of Roc Transformation" = "2 巨鹏变形祝福"
"3 Blessing of Dragon Transformation" = "3 巨龙变形祝福"
"4 Blessing of Magic Powers" = "4 魔法能力祝福"
"air" = "空气"
"Airblast" = "空气冲击"
"Altar of Blessings" = "祝福祭坛"
"Blessing" = "祝福"
"Blessing of Dragon Transformation" = "巨龙变形祝福"
"Blessing of Magic" = "魔法祝福"
"Blessing of Regeneration" = "再生祝福"
"Blessing of Roc Transformation" = "巨鹏变形祝福"
"cast Airblast" = "施放空气冲击"
"cast Fireball" = "施放火球术"
"cast Frostbolt" = "施放寒冰箭"
"cast Polymorph" = "施放变形术"
"Dragonblessed" = "巨龙祝福者"
"Fireball" = "火球术"
"Frostbolt" = "寒冰箭"
"FROSTBOLT SLOW" = "寒冰箭减速"
"ice bolt" = "冰箭"
"learn secret of Magical powers" = "学习魔法能力的奥秘"
"learn secret of rapid regeneration" = "学习快速再生的奥秘"
"learn secrets of Dragon transformation" = "学习巨龙变形的奥秘"
"learn secrets of Roc transformation" = "学习巨鹏变形的奥秘"
"learning secrets of Dragon transformation" = "正在学习巨龙变形的奥秘"
"learning secrets of Magical powers" = "正在学习魔法能力的奥秘"
"learning secrets of rapid regeneration" = "正在学习快速再生的奥秘"
"learning secrets of Roc transformation" = "正在学习巨鹏变形的奥秘"
"lightning" = "闪电"
"liquidized air" = "液化空气"
"magic aura" = "魔法灵气"
"Magic Powers" = "魔法能力"
"Polymorph" = "变形术"
"Rapid Regeneration" = "快速再生"
"Regenblessed" = "再生祝福者"
"Rocblessed" = "巨鹏祝福者"
"Shapeshift Dragon" = "巨龙变形"
"Shapeshift Roc" = "巨鹏变形"
"solidified air" = "凝固空气"
"Spellblessed" = "法术祝福者"
"steam" = "蒸汽"
"The Altar of Blessings" = "祝福祭坛"
"Transform into a Dragon" = "变身为巨龙"
"Transform into a Roc" = "变身为巨鹏"
"Tribute of Artifacts" = "献上神器"
"Vanish" = "隐身"
"water" = "水"
"Instructions for a Blessing" = "祝福仪式指南"
"the secrets of rapid regeneration" = "快速再生的奥秘"
"the secrets of roc transformation" = "巨鹏变形的奥秘"
"the secrets of dragon transformation" = "巨龙变形的奥秘"
"the secrets of magic powers" = "魔法能力的奥秘"
" A ritual altar where artifacts are offered as tributes in return for power" = "在此献上神器作为贡品，以换取力量的祭仪祭坛。"
"target" = "目标"
