base = "materials::state"

[[rulesets]]
name = "adjective"
[rulesets.rules]
"{::materials::subscribed_brewing}" = "{::materials::subscribed_brewing}"

[[rulesets]]
name = "shared::main"
[rulesets.rules]
"{::materials::subscribed_brewing}" = "{::materials::subscribed_brewing}"

