base = "materials::subscribed_smoking"

[[rulesets]]
[rulesets.rules]
"Adds smoking of various types to the game." = "为游戏加入多种吸烟方式。"
"apple shisha" = "苹果水烟料"
"apple shisha smoke" = "苹果水烟料烟雾"
"apricot shisha" = "杏水烟料"
"apricot shisha smoke" = "杏水烟料烟雾"
"ash shisha" = "白蜡树水烟料"
"ash shisha smoke" = "白蜡树水烟料烟雾"
"asparagus shisha" = "芦笋水烟料"
"asparagus shisha smoke" = "芦笋水烟料烟雾"
"avocado shisha" = "鳄梨水烟料"
"avocado shisha smoke" = "鳄梨水烟料烟雾"
"bambara groundnut shisha" = "班巴拉花生水烟料"
"bambara groundnut shisha smoke" = "班巴拉花生水烟料烟雾"
"banana shisha" = "香蕉水烟料"
"banana shisha smoke" = "香蕉水烟料烟雾"
"bayberry shisha" = "杨梅水烟料"
"bayberry shisha smoke" = "杨梅水烟料烟雾"
"bilberry shisha" = "越橘水烟料"
"bilberry shisha smoke" = "越橘水烟料烟雾"
"bitter melon shisha" = "苦瓜水烟料"
"bitter melon shisha smoke" = "苦瓜水烟料烟雾"
"bitter orange shisha" = "苦橙水烟料"
"bitter orange shisha smoke" = "苦橙水烟料烟雾"
"blackberry shisha" = "黑莓水烟料"
"blackberry shisha smoke" = "黑莓水烟料烟雾"
"blueberry shisha" = "蓝莓水烟料"
"blueberry shisha smoke" = "蓝莓水烟料烟雾"
"boiling green dragon salve" = "沸腾的绿龙药膏"
"cacao shisha" = "可可水烟料"
"cacao shisha smoke" = "可可水烟料烟雾"
"caper shisha" = "刺山柑水烟料"
"caper shisha smoke" = "刺山柑水烟料烟雾"
"carambola shisha" = "杨桃水烟料"
"carambola shisha smoke" = "杨桃水烟料烟雾"
"cashew shisha" = "腰果水烟料"
"cashew shisha smoke" = "腰果水烟料烟雾"
"cherry shisha" = "樱桃水烟料"
"cherry shisha smoke" = "樱桃水烟料烟雾"
"chewing pipe-weed" = "嚼烟斗草"
"chillum" = "直筒烟斗"
"chillums" = "直筒烟斗"
"citron shisha" = "香橼水烟料"
"citron shisha smoke" = "香橼水烟料烟雾"
"coffee shisha" = "咖啡水烟料"
"coffee shisha smoke" = "咖啡水烟料烟雾"
"cranberry shisha" = "蔓越莓水烟料"
"cranberry shisha smoke" = "蔓越莓水烟料烟雾"
"cucumber shisha" = "黄瓜水烟料"
"cucumber shisha smoke" = "黄瓜水烟料烟雾"
"custard-apple shisha" = "番荔枝水烟料"
"custard-apple shisha smoke" = "番荔枝水烟料烟雾"
"date palm shisha" = "枣椰水烟料"
"date palm shisha smoke" = "枣椰水烟料烟雾"
"desert lime shisha" = "沙漠莱檬水烟料"
"desert lime shisha smoke" = "沙漠莱檬水烟料烟雾"
"doesn't feel so good" = "感觉不太舒服"
"dried flower" = "干花"
"dried flower smoke" = "干花烟雾"
"drink an extract" = "饮用提取物"
"drink essence of tumult" = "饮用躁动精华"
"drink golden salve" = "饮用金色药膏"
"drink green dragon salve" = "饮用绿龙药膏"
"drink philosophers lament" = "饮用哲人之殇"
"drink warbow tincture" = "饮用战弓酊剂"
"drinking essence of tumult" = "饮用躁动精华"
"drinking golden salve" = "饮用金色药膏"
"drinking green dragon salve" = "饮用绿龙药膏"
"drinking opium latex" = "饮用鸦片乳汁"
"drinking philosophers lament" = "饮用哲人之殇"
"drinking warbow tincture" = "饮用战弓酊剂"
"dry hemp flowers into marijuana" = "将大麻花干燥为大麻干花"
"dry pipe-weed leaves into chewing pipe-weed" = "将烟斗草叶干燥为嚼烟"
"durian shisha" = "榴莲水烟料"
"durian shisha smoke" = "榴莲水烟料烟雾"
"eating hashish" = "食用大麻脂"
"eating hemp buds" = "食用大麻花芽"
"eating hemp flower" = "食用大麻花"
"eating hemp leaf" = "食用大麻叶"
"eating marijuana" = "食用大麻干花"
"eggplant shisha" = "茄子水烟料"
"eggplant shisha smoke" = "茄子水烟料烟雾"
"essence of tumult" = "躁动精华"
"essence of tumult smoke" = "躁动精华烟雾"
"extract essense of tumult" = "提取躁动精华"
"extract green dragon salve" = "提取绿龙药膏"
"extract opium latex" = "提取鸦片乳汁"
"extract philosophers lament" = "提取哲人之殇"
"extract warbow tincture" = "提取战弓酊剂"
"finger lime shisha" = "指橙水烟料"
"finger lime shisha smoke" = "指橙水烟料烟雾"
"frozen essence of tumult" = "结冻的躁动精华"
"frozen green dragon salve" = "结冻的绿龙药膏"
"frozen opium latex" = "结冻的鸦片乳汁"
"frozen philosopher's lament" = "结冻的哲人之殇"
"frozen warbow tincture" = "结冻的战弓酊剂"
"get lung cancer roll begin" = "开始肺癌判定"
"get oil" = "获取油"
"get reefer madness roll begin" = "开始大麻性精神错乱判定"
"get royal jelly" = "获取蜂王浆"
"get syrup" = "获取糖浆"
"get test supplies" = "获取试用物资"
"get water" = "获取水"
"grape shisha" = "葡萄水烟料"
"grape shisha smoke" = "葡萄水烟料烟雾"
"green dragon salve" = "绿龙药膏"
"guava shisha" = "番石榴水烟料"
"guava shisha smoke" = "番石榴水烟料烟雾"
"hash" = "大麻脂"
"hash smoke" = "大麻脂烟雾"
"hashish" = "大麻脂"
"hashish resin" = "大麻树脂"
"hashish smoke" = "大麻脂烟雾"
"hemlock" = "毒芹"
"hemlock flower" = "毒芹花"
"hemlock flowers" = "毒芹花"
"hemlock seed" = "毒芹种子"
"hemlock seeds" = "毒芹种子"
"hemp" = "大麻"
"hemp bud" = "大麻花芽"
"hemp buds" = "大麻花芽"
"hemp bulb" = "大麻球茎"
"hemp cigar" = "大麻雪茄"
"hemp cigars" = "大麻雪茄"
"hemp flower" = "大麻花"
"hemp flowers" = "大麻花"
"hemp smoke" = "大麻烟雾"
"hemp vapor" = "大麻蒸气"
"Hookah" = "水烟壶"
"horned melon shisha" = "刺角瓜水烟料"
"horned melon shisha smoke" = "刺角瓜水烟料烟雾"
"inhaling apple shisha smoke" = "吸入苹果水烟料烟雾"
"inhaling apricot shisha smoke" = "吸入杏水烟料烟雾"
"inhaling ash shisha smoke" = "吸入白蜡树水烟料烟雾"
"inhaling asparagus shisha smoke" = "吸入芦笋水烟料烟雾"
"inhaling avocado shisha smoke" = "吸入鳄梨水烟料烟雾"
"inhaling bambara_groundnut shisha smoke" = "吸入班巴拉花生水烟料烟雾"
"inhaling banana shisha smoke" = "吸入香蕉水烟料烟雾"
"inhaling bayberry shisha smoke" = "吸入杨梅水烟料烟雾"
"inhaling bilberry shisha smoke" = "吸入越橘水烟料烟雾"
"inhaling bitter melon shisha smoke" = "吸入苦瓜水烟料烟雾"
"inhaling bitter orange shisha smoke" = "吸入苦橙水烟料烟雾"
"inhaling blackberry shisha smoke" = "吸入黑莓水烟料烟雾"
"inhaling blueberry shisha smoke" = "吸入蓝莓水烟料烟雾"
"inhaling cacao shisha smoke" = "吸入可可水烟料烟雾"
"inhaling caper shisha smoke" = "吸入刺山柑水烟料烟雾"
"inhaling carambola shisha smoke" = "吸入杨桃水烟料烟雾"
"inhaling cashew shisha smoke" = "吸入腰果水烟料烟雾"
"inhaling cherry shisha smoke" = "吸入樱桃水烟料烟雾"
"inhaling citron shisha smoke" = "吸入香橼水烟料烟雾"
"inhaling coffee shisha smoke" = "吸入咖啡水烟料烟雾"
"inhaling cranberry shisha smoke" = "吸入蔓越莓水烟料烟雾"
"inhaling cucumber shisha smoke" = "吸入黄瓜水烟料烟雾"
"inhaling custard-apple shisha smoke" = "吸入番荔枝水烟料烟雾"
"inhaling date palm shisha smoke" = "吸入枣椰水烟料烟雾"
"inhaling desert lime shisha smoke" = "吸入沙漠莱檬水烟料烟雾"
"inhaling durian shisha smoke" = "吸入榴莲水烟料烟雾"
"inhaling eggplant shisha smoke" = "吸入茄子水烟料烟雾"
"inhaling essence of tumult" = "吸入躁动精华"
"inhaling finger lime shisha smoke" = "吸入指橙水烟料烟雾"
"inhaling golden salve" = "吸入金色药膏"
"inhaling grape shisha smoke" = "吸入葡萄水烟料烟雾"
"inhaling green dragon salve" = "吸入绿龙药膏"
"inhaling guava shisha smoke" = "吸入番石榴水烟料烟雾"
"inhaling hashish smoke" = "吸入大麻脂烟雾"
"inhaling horned melon shisha smoke" = "吸入刺角瓜水烟料烟雾"
"inhaling kapok shisha smoke" = "吸入木棉水烟料烟雾"
"inhaling kumquat shisha smoke" = "吸入金橘水烟料烟雾"
"inhaling lime shisha smoke" = "吸入莱檬水烟料烟雾"
"inhaling lychee shisha smoke" = "吸入荔枝水烟料烟雾"
"inhaling mahogany shisha smoke" = "吸入桃花心木水烟料烟雾"
"inhaling mango shisha smoke" = "吸入芒果水烟料烟雾"
"inhaling mangrove shisha smoke" = "吸入红树水烟料烟雾"
"inhaling maple shisha smoke" = "吸入枫树水烟料烟雾"
"inhaling marijuana smoke" = "吸入大麻干花烟雾"
"inhaling muskmelon shisha smoke" = "吸入甜瓜水烟料烟雾"
"inhaling olive shisha smoke" = "吸入橄榄水烟料烟雾"
"inhaling opium smoke" = "吸入鸦片烟雾"
"inhaling orange shisha smoke" = "吸入橙水烟料烟雾"
"inhaling papaya shisha smoke" = "吸入番木瓜水烟料烟雾"
"inhaling paradise nut shisha smoke" = "吸入巴西坚果水烟料烟雾"
"inhaling passion fruit shisha smoke" = "吸入百香果水烟料烟雾"
"inhaling peach shisha smoke" = "吸入桃水烟料烟雾"
"inhaling peanut shisha smoke" = "吸入花生水烟料烟雾"
"inhaling pear shisha smoke" = "吸入梨水烟料烟雾"
"inhaling pepper shisha smoke" = "吸入辣椒水烟料烟雾"
"inhaling persimmon shisha smoke" = "吸入柿水烟料烟雾"
"inhaling philosophers lament" = "吸入哲人之殇"
"inhaling pineapple shisha smoke" = "吸入菠萝水烟料烟雾"
"inhaling pipe-weed smoke" = "吸入烟斗草烟雾"
"inhaling plum shisha smoke" = "吸入李水烟料烟雾"
"inhaling pomegranate shisha smoke" = "吸入石榴水烟料烟雾"
"inhaling pomelo shisha smoke" = "吸入柚水烟料烟雾"
"inhaling rambutan shisha smoke" = "吸入红毛丹水烟料烟雾"
"inhaling raspberry shisha smoke" = "吸入树莓水烟料烟雾"
"inhaling round lime shisha smoke" = "吸入圆莱檬水烟料烟雾"
"inhaling saguaro shisha smoke" = "吸入巨刺柱水烟料烟雾"
"inhaling sand pear shisha smoke" = "吸入砂梨水烟料烟雾"
"inhaling squash shisha smoke" = "吸入南瓜水烟料烟雾"
"inhaling strawberry shisha smoke" = "吸入草莓水烟料烟雾"
"inhaling tea shisha smoke" = "吸入茶水烟料烟雾"
"inhaling tomatillo shisha smoke" = "吸入酸浆水烟料烟雾"
"inhaling tomato shisha smoke" = "吸入番茄水烟料烟雾"
"inhaling warbow tincture" = "吸入战弓酊剂"
"inhaling watermelon shisha smoke" = "吸入西瓜水烟料烟雾"
"inhaling willow shisha smoke" = "吸入柳树水烟料烟雾"
"inhaling winter melon shisha smoke" = "吸入冬瓜水烟料烟雾"
"injecting opium latex" = "注射鸦片乳汁"
"injecting philosophers lament" = "注射哲人之殇"
"joint" = "大麻卷烟"
"joints" = "大麻卷烟"
"kapok shisha" = "木棉水烟料"
"kapok shisha smoke" = "木棉水烟料烟雾"
"kumquat shisha" = "金橘水烟料"
"kumquat shisha smoke" = "金橘水烟料烟雾"
"leaf" = "叶"
"leaf smoke" = "叶烟雾"
"leaf vapor" = "叶蒸气"
"lime shisha" = "莱檬水烟料"
"lime shisha smoke" = "莱檬水烟料烟雾"
"lung cancer" = "肺癌"
"lung cancer roll one" = "肺癌判定一"
"lung cancer roll two" = "肺癌判定二"
"lychee shisha" = "荔枝水烟料"
"lychee shisha smoke" = "荔枝水烟料烟雾"
"mahogany shisha" = "桃花心木水烟料"
"mahogany shisha smoke" = "桃花心木水烟料烟雾"
"make bismuth pipe" = "制作铋制烟斗"
"make bone chillum" = "制作骨制直筒烟斗"
"make bone pipe" = "制作骨制烟斗"
"make brass pipe" = "制作黄铜制烟斗"
"make bronze pipe" = "制作青铜制烟斗"
"make clay chillum" = "制作陶土制直筒烟斗"
"make clay pipe" = "制作陶土制烟斗"
"make copper pipe" = "制作铜制烟斗"
"make electrum pipe" = "制作金银合金制烟斗"
"make glass pipe" = "制作玻璃制烟斗"
"make gold pipe" = "制作金制烟斗"
"make horn chillum" = "制作角制直筒烟斗"
"make horn pipe" = "制作角制烟斗"
"make iron pipe" = "制作铁制烟斗"
"make lead pipe" = "制作铅制烟斗"
"make mist" = "制造水雾"
"make platinum pipe" = "制作铂金制烟斗"
"make rock pipe" = "制作石制烟斗"
"make rose gold pipe" = "制作玫瑰金制烟斗"
"make rose steel pipe" = "制作玫瑰钢制烟斗"
"make shell chillum" = "制作贝壳制直筒烟斗"
"make shell pipe" = "制作贝壳制烟斗"
"make silver pipe" = "制作银制烟斗"
"make wooden pipe" = "制作木制烟斗"
"mango shisha" = "芒果水烟料"
"mango shisha smoke" = "芒果水烟料烟雾"
"mangrove shisha" = "红树水烟料"
"mangrove shisha smoke" = "红树水烟料烟雾"
"maple shisha" = "枫树水烟料"
"maple shisha smoke" = "枫树水烟料烟雾"
"marijuana" = "大麻干花"
"marijuana resin" = "大麻干花树脂"
"marijuana smoke" = "大麻干花烟雾"
"melted shisha" = "熔化的水烟料"
"muskmelon shisha" = "甜瓜水烟料"
"muskmelon shisha smoke" = "甜瓜水烟料烟雾"
"olive shisha" = "橄榄水烟料"
"olive shisha smoke" = "橄榄水烟料烟雾"
"opium latex" = "鸦片乳汁"
"opium smoke" = "鸦片烟雾"
"orange shisha" = "橙水烟料"
"orange shisha smoke" = "橙水烟料烟雾"
"papaya shisha" = "番木瓜水烟料"
"papaya shisha smoke" = "番木瓜水烟料烟雾"
"paradise nut shisha" = "巴西坚果水烟料"
"paradise nut shisha smoke" = "巴西坚果水烟料烟雾"
"passion fruit shisha" = "百香果水烟料"
"passion fruit shisha smoke" = "百香果水烟料烟雾"
"peach shisha" = "桃水烟料"
"peach shisha smoke" = "桃水烟料烟雾"
"peanut shisha" = "花生水烟料"
"peanut shisha smoke" = "花生水烟料烟雾"
"pear shisha" = "梨水烟料"
"pear shisha smoke" = "梨水烟料烟雾"
"pepper shisha" = "辣椒水烟料"
"pepper shisha smoke" = "辣椒水烟料烟雾"
"persimmon shisha" = "柿水烟料"
"persimmon shisha smoke" = "柿水烟料烟雾"
"philosopher's lament" = "哲人之殇"
"philosopher's lament vapor" = "哲人之殇蒸气"
"pineapple shisha" = "菠萝水烟料"
"pineapple shisha smoke" = "菠萝水烟料烟雾"
"pipe" = "烟斗"
"pipe-weed" = "烟斗草"
"pipe-weed cigar" = "烟斗草雪茄"
"pipe-weed cigars" = "烟斗草雪茄"
"pipe-weed flower" = "烟斗草花"
"pipe-weed flowers" = "烟斗草花"
"pipe-weed leaf" = "烟斗草叶"
"pipe-weed leaves" = "烟斗草叶"
"pipe-weed smoke" = "烟斗草烟雾"
"pipe-weed vapor" = "烟斗草蒸气"
"pipes" = "烟斗"
"plum shisha" = "李水烟料"
"plum shisha smoke" = "李水烟料烟雾"
"pomegranate shisha" = "石榴水烟料"
"pomegranate shisha smoke" = "石榴水烟料烟雾"
"pomelo shisha" = "柚水烟料"
"pomelo shisha smoke" = "柚水烟料烟雾"
"poppy" = "罂粟"
"poppy bud" = "罂粟花芽"
"poppy buds" = "罂粟花芽"
"poppy flower" = "罂粟花"
"poppy flowers" = "罂粟花"
"poppy leaf" = "罂粟叶"
"poppy leaves" = "罂粟叶"
"poppy seed" = "罂粟种子"
"poppy seeds" = "罂粟种子"
"Potion Bench" = "药剂台"
"press aromatics into shisha" = "将芳香植物压制为水烟料"
"press hashish" = "压制大麻脂"
"puff chillum smoke" = "吐出直筒烟斗烟雾"
"puff cigar smoke" = "吐出雪茄烟雾"
"puff joint smoke" = "吐出大麻卷烟烟雾"
"puff pipe smoke" = "吐出烟斗烟雾"
"puffs chillum smoke" = "吐出直筒烟斗烟雾"
"puffs cigar smoke" = "吐出雪茄烟雾"
"puffs joint smoke" = "吐出大麻卷烟烟雾"
"puffs pipe smoke" = "吐出烟斗烟雾"
"rambutan shisha" = "红毛丹水烟料"
"rambutan shisha smoke" = "红毛丹水烟料烟雾"
"raspberry shisha" = "树莓水烟料"
"raspberry shisha smoke" = "树莓水烟料烟雾"
"really doesn't feel so good" = "感觉非常不舒服"
"reefer madness" = "大麻性精神错乱"
"refer madness roll one" = "大麻性精神错乱判定一"
"refer madness roll two" = "大麻性精神错乱判定二"
"roll hemp cigars" = "卷制大麻雪茄"
"roll joints" = "卷制大麻卷烟"
"roll pipe-weed cigars" = "卷制烟斗草雪茄"
"round lime shisha" = "圆莱檬水烟料"
"round lime shisha smoke" = "圆莱檬水烟料烟雾"
"saguaro shisha" = "巨刺柱水烟料"
"saguaro shisha smoke" = "巨刺柱水烟料烟雾"
"sand pear shisha" = "砂梨水烟料"
"sand pear shisha smoke" = "砂梨水烟料烟雾"
"shisha" = "水烟料"
"shisha smoke" = "水烟料烟雾"
"smoke" = "烟雾"
"Smoke chillum" = "抽直筒烟斗"
"Smoke cigar" = "抽雪茄"
"smoke hashish" = "抽大麻脂"
"smoke hemp" = "抽大麻"
"Smoke joint" = "抽大麻卷烟"
"smoke marijuana" = "抽大麻干花"
"Smoke pipe" = "抽烟斗"
"smoke pipe-weed" = "抽烟斗草"
"smoke shisha" = "抽水烟料"
"smoking a chillum" = "正在抽直筒烟斗"
"smoking a hemp cigar" = "正在抽大麻雪茄"
"smoking a joint" = "正在抽大麻卷烟"
"smoking a pipe" = "正在抽烟斗"
"smoking a pipe-weed cigar" = "正在抽烟斗草雪茄"
"snuff" = "鼻烟"
"squash shisha" = "南瓜水烟料"
"squash shisha smoke" = "南瓜水烟料烟雾"
"strawberry shisha" = "草莓水烟料"
"strawberry shisha smoke" = "草莓水烟料烟雾"
"tea shisha" = "茶水烟料"
"tea shisha smoke" = "茶水烟料烟雾"
"tomatillo shisha" = "酸浆水烟料"
"tomatillo shisha smoke" = "酸浆水烟料烟雾"
"tomato shisha" = "番茄水烟料"
"tomato shisha smoke" = "番茄水烟料烟雾"
"Topples' Smoking" = "Topples 吸烟"
"vapor" = "蒸气"
"vaporize an extract" = "雾化提取物"
"vaporize essence of tumult" = "雾化躁动精华"
"vaporize golden salve" = "雾化金色药膏"
"vaporize green dragon salve" = "雾化绿龙药膏"
"vaporize philosophers lament" = "雾化哲人之殇"
"vaporize warbow tincture" = "雾化战弓酊剂"
"warbow tincture" = "战弓酊剂"
"warbow tincture vapor" = "战弓酊剂蒸气"
"watermelon shisha" = "西瓜水烟料"
"watermelon shisha smoke" = "西瓜水烟料烟雾"
"willow shisha" = "柳树水烟料"
"willow shisha smoke" = "柳树水烟料烟雾"
"winter melon shisha" = "冬瓜水烟料"
"winter melon shisha smoke" = "冬瓜水烟料烟雾"
"inhaling hemp bud smoke" = "吸入大麻花芽烟雾"
"inhaling hemp flower smoke" = "吸入大麻花烟雾"
"inhaling hemp leaf smoke" = "吸入大麻叶烟雾"
"inhaling palm shisha smoke" = "吸入棕榈水烟料烟雾"
"palm shisha" = "棕榈水烟料"
"palm shisha smoke" = "棕榈水烟料烟雾"
"smoke opium" = "抽鸦片"
"poppies" = "罂粟"
"Create clouds of aromatic gas." = "制造芳香气体云团。"
"Make a dwarf drink a potion." = "让一名矮人喝下药剂。"
"target" = "目标"
