base = "creatures::caste"

[[rulesets]]
name = "singular"
[rulesets.rules]
"{::creatures::name::whaleys_dogs::singular}" = "{::creatures::name::whaleys_dogs::singular}"

[[rulesets]]
name = "plural"
[rulesets.rules]
"{::creatures::name::whaleys_dogs::plural}" = "{::creatures::name::whaleys_dogs::plural}"
