base = "creatures::name"

[[rulesets]]
name = "singular"
[rulesets.rules]
"{::whaleys_dogs::names::singular}" = "{::whaleys_dogs::names::singular}"

[[rulesets]]
name = "plural"
[rulesets.rules]
"{::whaleys_dogs::names::plural}" = "{::whaleys_dogs::names::plural}"
