base = "better_glazing::materials"

[[rulesets]]
[rulesets.rules]
"{glaze}" = "{glaze}"
"{ceramic}" = "{ceramic}"
"glaze" = "釉料"
"molten glaze" = "熔融釉料"
"boiling glaze" = "沸腾釉料"
"glazed ceramic" = "上釉陶瓷"

[[rulesets]]
name = "glaze"
[rulesets.rules]
"gold glaze" = "金釉"
"silver glaze" = "银釉"
"tin glaze" = "锡釉"
"ash glaze" = "灰釉"
"hematite glaze" = "赤铁矿釉"
"limonite glaze" = "褐铁矿釉"
"magnetite glaze" = "磁铁矿釉"
"galena glaze" = "方铅矿釉"
"malachite glaze" = "孔雀石釉"
"garnierite glaze" = "硅镁镍矿釉"
"sphalerite glaze" = "闪锌矿釉"
"cobaltite glaze" = "辉钴矿釉"
"pyrolusite glaze" = "软锰矿釉"
"chromite glaze" = "铬铁矿釉"
"rutile glaze" = "金红石釉"
"ilmenite glaze" = "钛铁矿釉"
"stibnite glaze" = "辉锑矿釉"
"orpiment glaze" = "雌黄釉"
"realgar glaze" = "雄黄釉"
"cinnabar glaze" = "朱砂釉"
"salt glaze" = "盐釉"
"microcline glaze" = "微斜长石釉"
"pitchblende glaze" = "沥青铀矿釉"
"bone ash glaze" = "骨灰釉"
"rose glaze" = "玫瑰色釉"
"flax glaze" = "亚麻色釉"
"gray glaze" = "灰色釉"
"moss green glaze" = "苔绿色釉"
"maroon glaze" = "栗红色釉"
"olive glaze" = "橄榄色釉"
"chestnut glaze" = "栗色釉"
"mint green glaze" = "薄荷绿色釉"
"aquamarine glaze" = "碧蓝色釉"
"sky blue glaze" = "天蓝色釉"
"pink glaze" = "粉红色釉"
"lilac glaze" = "丁香紫色釉"
"peach glaze" = "桃色釉"
"sea foam glaze" = "海沫绿色釉"
"turquoise glaze" = "绿松石色釉"
"teal glaze" = "蓝绿色釉"
"violet glaze" = "紫罗兰色釉"

[[rulesets]]
name = "ceramic"
[rulesets.rules]
"{color} {kind}" = "{color}{kind}"

[[rulesets]]
name = "kind"
[rulesets.rules]
"earthenware" = "瓦陶"
"stoneware" = "炻瓷"
"porcelain" = "瓷器"

[[rulesets]]
name = "color"
[rulesets.rules]
"cream" = "奶油色"
"fern green" = "蕨绿色"
"gold" = "金色"
"silver" = "银色"
"rust" = "铁锈色"
"ochre" = "赭黄色"
"charcoal" = "炭灰色"
"amber" = "琥珀色"
"emerald" = "祖母绿色"
"slate gray" = "石板灰色"
"white" = "白色"
"cobalt" = "钴蓝色"
"plum" = "李紫色"
"apple green" = "苹果绿色"
"tan" = "黄褐色"
"dark brown" = "深棕色"
"golden yellow" = "金黄色"
"lemon" = "柠檬黄色"
"orange" = "橙色"
"vermilion" = "朱红色"
"ash gray" = "灰烬色"
"jade" = "翡翠绿色"
"pumpkin" = "南瓜橙色"
"pearl" = "珍珠白色"
"rose" = "玫瑰色"
"flax" = "亚麻色"
"gray" = "灰色"
"moss green" = "苔绿色"
"maroon" = "栗红色"
"olive" = "橄榄色"
"chestnut" = "栗色"
"mint green" = "薄荷绿色"
"aquamarine" = "碧蓝色"
"sky blue" = "天蓝色"
"pink" = "粉红色"
"lilac" = "丁香紫色"
"peach" = "桃色"
"sea foam" = "海沫绿色"
"turquoise" = "绿松石色"
"teal" = "蓝绿色"
"violet" = "紫罗兰色"
